server:
  port: 8080
spring:
  application:
    name: synthesize
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/utilAndTest?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
mybatis:
  mapper-locations: com/synthesize/test/mybatis/mapper/**Mapper.xml
  type-aliases-package: com.synthesize.test.mybatis.demo